<!DOCTYPE html>
<html lang="en">

<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <script src="https://kit.fontawesome.com/4489d876da.js" crossorigin="anonymous"></script>
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.6.0/jquery.min.js"></script>
    <script src="./js/LoadMoreImages.js?v=<?= time(); ?>" type="text/javascript" defer></script>
    <script src="./js/PostScriptFunctions.js?v=<?= time(); ?>" type="text/javascript" defer></script>
    <script src="./js/NavigationMenu.js?v=<?= time(); ?>" type="text/javascript" defer></script>
    <script src="./js/fileupload/simpledropit.min.js?v=<?= time(); ?>" type="text/javascript"></script>
    <script src="./js/TagSelect.js?v=<?=time()?>" type="text/javascript" defer></script>
    <link rel="stylesheet" href="css/style.css?v=<?= time(); ?>" type="text/css">
    
    <link rel="stylesheet" href="./css/fileupload/simpledropit.css?v=<?= time()?>">
    <title>Document</title>
</head>

<body>
    <?php require("./phtml/navigation.phtml"); ?>
    <div class="back-button"><a href="index.php"><i class="fa-solid fa-arrow-left"></i></a></div>
    <div class="form-wrapper">
    <div class="addpost-header"><h1>EVENTON</h1></div>
        <form method="post" class="account-form addpost" enctype="multipart/form-data">
            <h2>Nahrát příspěvek</h2>
            <div class="form-content">
                <div class="post-image">
                    <div class="image">
                        <div class="sd-box sd-advanced-upload addpost">
                            <div class="sd-box-wrapper">
                                <div class="sd-label-wrapper">
                                    <span class="sd-box-file-name" style="display: none;"></span>
                                    <label class="sd-label"><span class="sd-box-browse-file">File</span>
                                        <div id="imagePreview">
                                            <div class="image-upload-box">
                                                <i class="fa-solid fa-cloud-arrow-up"></i>
                                                <span>Klikněte pro nahrání</span>
                                            </div>
                                        </div>
                                    </label>
                                    <input type="file" name="image" id="image">
                                </div>
                            </div>
                        </div>
                    </div>
                </div>
                <div class="post-info">
                    <div class="form-item">
                        <label for="comment">Komentář</label>
                        <textarea name="comment" id="comment"></textarea>
                        <div class="char-counter"><span id="char-counter-text">0/0</span></div>
                    </div>
                    <div class="form-item tag-container">
                        <h3>Tags, max. 10</h3>
                        <div class="tag-select">
                            <input type="text" class="tag-input">
                        </div>
                        <div class="tag-autocomplete">
                        </div>
                    </div>  
                    <div class="submit-container form-item">
                        <div><?php $user_manager->PrintErrors()?></div>
                        <input type="submit" value="Potvrdit" name="addpost">
                    </div>
                </div>
            </div>
        </form>
    </div>
    <script>
        $(function() {
            new SimpleDropit($('#image')[0]);
            $("#image").on("change", function()
            {
                var files = !!this.files ? this.files : [];
                if (!files.length || !window.FileReader) return;
                if (/^image/.test( files[0].type)){
                    var reader = new FileReader();
                    reader.readAsDataURL(files[0]);
                    
                    reader.onloadend = function(){
                        $("#imagePreview").html("<img class='image-preview' src="+this.result+" alt='image-preview'>")
                    }
                }
            });

            max_length = 300;
            ChangeCounterText(0);
            $()
            $("#comment").on("input", function() {
                $(this).val($(this).val().substr(0, max_length));
                ChangeCounterText($(this).val().length);
            });
        });

        function ChangeCounterText(amount){
            $("#char-counter-text").html(amount + "/" + max_length);
        }

        function ReloadSearchResults(search_value){
            $.ajax({
                type: "GET",
                url: "./php/post_search_manager.php?search_value="+ search_value + "&search_data="+1,
                success: function (r) {  
                    
                }        
            });
        }
    </script>
</body>

</html>