<!DOCTYPE html>
<html lang="en">

<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <script src="https://kit.fontawesome.com/4489d876da.js" crossorigin="anonymous"></script>
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.6.0/jquery.min.js"></script>
    <script src="./js/LoadMoreImages.js?v=<?= time(); ?>" type="text/javascript" defer></script>
    <script src="./js/PostScriptFunctions.js?v=<?= time(); ?>" type="text/javascript" defer></script>
    <script src="./js/NavigationMenu.js?v=<?= time(); ?>" type="text/javascript" defer></script>
    <script src="./js/fileupload/simpledropit.min.js?v=<?= time(); ?>" type="text/javascript"></script>
    <link rel="stylesheet" href="css/style.css?v=<?= time(); ?>" type="text/css">
    
    <link rel="stylesheet" href="./css/fileupload/simpledropit.css?v=<?= time()?>">
    <title>Document</title>
</head>

<body>
    <?php require("./phtml/navigation.phtml"); ?>
    <div class="back-button"><a href="index.php"><i class="fa-solid fa-arrow-left"></i></a></div>
    <?php $user_manager->PrintErrors(); ?>
    <div class="form-wrapper">
    <div class="addpost-header"><h1>EVENTON</h1></div>
        <form method="post" class="account-form addpost" enctype="multipart/form-data">
            <h2>Nahrátí příspěvku</h2>
            <div class="form-content">
                <div class="post-image">
                    
                    <div class="image">
                        <label for="icon_upload">Obrázek</label>
                        <div class="sd-box sd-advanced-upload addpost">
                            <div class="sd-box-wrapper">
                                <div class="sd-label-wrapper">
                                    <span class="sd-box-file-name" style="display: none;"></span>
                                    <label class="sd-label"><span class="sd-box-browse-file">File</span>
                                        <div id="imagePreview">
                                            <div class="image-upload-box">
                                                <i class="fa-solid fa-cloud-arrow-up"></i>
                                                <span>Klikněte pro nahrání</span>
                                            </div>
                                        </div>
                                    </label>
                                    <input type="file" name="image" id="image">
                                </div>
                                <!--<div id="imagePreview"></div>-->
                            </div>
                        </div>
                    </div>
                </div>
                <div class="post-info">
                    <div class="form-item">
                        <label for="comment">Komentář</label>
                        <textarea name="comment" id="comment"></textarea>
                        <div class="char-counter"><span id="char-counter-text">0/0</span></div>
                    </div>
                    <div class="form-item" style="display: inline">
                        <label for="private">Soukromý příspěvek</label>
                        <input type="checkbox" name="private" id="private">
                    </div>
                </div>
            </div>
            <div class="submit-container form-item">
                <input type="submit" value="Potvrdit" name="addpost">
            </div>
        </form>
    </div>
    <script>
        $(function() {
            new SimpleDropit($('#image')[0]);
            $("#image").on("change", function()
            {
                var files = !!this.files ? this.files : [];
                if (!files.length || !window.FileReader) return;
                if (/^image/.test( files[0].type)){
                    var reader = new FileReader();
                    reader.readAsDataURL(files[0]);
                    
                    reader.onloadend = function(){
                        $("#imagePreview").html("<img class='image-preview' src="+this.result+" alt='image-preview'>")
                    }
                }
            });

            max_length = 300;
            ChangeCounterText(0);
            $()
            $("#comment").on("keyup", function() {
                $(this).val($(this).val().substr(0, max_length));
                ChangeCounterText($(this).val().length);
            });
        });

        function ChangeCounterText(amount){
            $("#char-counter-text").html(amount + "/" + max_length);
        }
    </script>
</body>

</html>