<!DOCTYPE html>
<html lang="en">

<head>
    <?php require("./phtml/_defaultHeaderLinks.phtml"); ?>
    <script src="./js/min/NavigationMenu.min.js" type="text/javascript" defer></script>
    <script src="./js/fileupload/simpledropit.min.js" type="text/javascript"></script>
    <script src="./js/min/TagSelect.min.js" type="text/javascript" defer></script>
    <script src="./js/min/ImageShowOnUpload.min.js" type="text/javascript" defer></script>
    <script src="./js/min/CharCounter.min.js" type="text/javascript" defer></script>
    <link rel="stylesheet" href="./css/fileupload/simpledropit.css">
</head>

<body>
    <main>
        <?php require("./phtml/navigation.phtml"); ?>
        <div class="back-button"><a href="index.php"><i class="fa-solid fa-arrow-left"></i></a></div>
        <div class="form-wrapper">
            <div class="addpost-header">
                <h1>EVENTON</h1>
            </div>
            <form method="post" class="account-form addpost" enctype="multipart/form-data">
                <h2>Nahrát příspěvek</h2>
                <div class="form-content">
                    <div class="post-image">
                        <div class="image">
                            <div class="sd-box sd-advanced-upload addpost">
                                <div class="sd-box-wrapper">
                                    <div class="sd-label-wrapper">
                                        <span class="sd-box-file-name" style="display: none;"></span>
                                        <label class="sd-label"><span class="sd-box-browse-file">File</span>
                                            <div id="imagePreview">
                                                <div class="image-upload-box">
                                                    <i class="fa-solid fa-cloud-arrow-up"></i>
                                                    <span>Klikněte pro nahrání</span>
                                                </div>
                                            </div>
                                        </label>
                                        <input type="file" name="image" id="image" accept="<?= implode(", ", UserManager::SUPPORTED_FILES)?>">
                                    </div>
                                </div>
                            </div>
                        </div>
                    </div>
                    <div class="post-info">
                        <div class="form-item">
                            <label for="comment" class="addpost-label"><span><i class="fa-solid fa-message"></i>Komentář</span></label>
                            <textarea name="comment" id="comment"><?php if(isset($_POST["comment"])) echo($_POST["comment"]);?></textarea>
                            <div class="char-counter"><span id="char-counter-text">0/0</span></div>
                        </div>
                        <div class="form-item tag-container">
                            <label class="addpost-label"><span><i class="fa-solid fa-tags"></i>Tags</span><span class="mutted">max. 10</span></label>
                            <div class="tag-select">
                                <input type="text" class="tag-input">
                            </div>
                            <div class="tag-autocomplete">
                            </div>
                        </div>
                        <div class="submit-container form-item">
                            <div><?php if($user_manager->GetErrorCount() > 0) {
                                echo('<i class="fa-solid fa-circle-exclamation error"></i>');
                                $user_manager->PrintErrors();
                            } ?></div>
                            <input type="submit" value="Potvrdit" name="addpost">
                        </div>
                    </div>
                </div>
            </form>
        </div>
    </main>
    <script>
        new SimpleDropit($('#image')[0]);
    </script>
</body>

</html>