<!DOCTYPE html>
<html lang="en">
<head>
    <?php require("./phtml/_defaultHeaderLinks.phtml"); ?>
    <script src="js/min/AdminFunctions.min.js" type="text/javascript" defer></script>
</head>
<body class="admin-page">
    <nav class="admin-nav">
        <ul class="admin-nav-ul">
            <li><a href="index.php" class="header"><i class="fa-solid fa-arrow-left-long" id="admin-nav-button"></i>ADMIN</a></li>
            <li><a class="admin-nav-link active" onclick="ChangeTableData(0, this)"><i class="fa-solid fa-users"></i>Uživatelé</a></li>
            <li><a class="admin-nav-link" onclick="ChangeTableData(1, this)"><i class="fa-solid fa-image"></i>Příspěvky</a></li>
            <li><a class="admin-nav-link" onclick="ChangeTableData(2, this)"><i class="fa-solid fa-tags"></i>Tagy</a></li>
        </ul>
    </nav>
    <main>
        <div class="content-container">
            <div class="admin-inputs">
                <input type="text" name="search" id="search" onchange="Search(this)">
            </div>
            <div class="data-wrapper">
                    <table class="data-table" id="0">
                        <thead class="table-header">
                        </thead>
                        <tbody class="database-data">
                        </tbody>
                </table>
            </div>
        </div>
    </main>
</body>
</html>
                        
                    