<meta charset="UTF-8">
<meta http-equiv="X-UA-Compatible" content="IE=edge">
<meta name="viewport" content="width=device-width, initial-scale=1.0">
<script src="./js/jquery/jquery-3.6.0.min.js"></script>
<link rel="stylesheet" href="./css/min/style.min.css" type="text/css">
<link rel="stylesheet" href="./css/fontawesome/css/all.min.css" rel="stylesheet">
<link rel="shortcut icon" href="./images/favicon.png" type="image/x-icon">
<title>Eventon</title>