<!DOCTYPE html>
<html lang="en">    
<head>        
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <script src="https://kit.fontawesome.com/4489d876da.js" crossorigin="anonymous"></script>
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.6.0/jquery.min.js"></script>
    <script src="./js/LoadMoreImages.js?v=<?= time(); ?>" type="text/javascript" defer></script>
    <script src="./js/PostScriptFunctions.js?v=<?= time(); ?>" type="text/javascript" defer></script>
    <script src="./js/NavigationMenu.js?v=<?=time(); ?>" type="text/javascript" defer></script>
    <link rel="stylesheet" href="css/style.css?v=<?= time(); ?>" type="text/css">
    <link rel="stylesheet" href="css/post-style.css?v=<?=time(); ?>" type="text/css">
    <title>Document</title>    
</head>
<body>
    <select id="post-filter" style="margin-top: 80px">
        <option value="0">Od nejnovějších</option>
        <option value="1">Od nejstarších</option>
        <option value="2">Od nejlépe hodnocených</option>
    </select>
    <div>
        <input type="text" id="post-search">
        <select>
            <option value="0">Uživatel</option>
            <option value="1">Tag</option>
        </select>
    </div>
    <main>
        <?php require("./phtml/navigation.phtml"); ?>
        <div id="posts-container">
        </div>
        <div id="loader-image" style="visibility:hidden;width:50px;margin:50px auto"><img src="images/LoadingGif.gif" style="width:50px;height:50px"alt=""></div>
    </main>
</body>
</html>