<!DOCTYPE html>
<html lang="en">

<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Document</title>
</head>

<body>
    <?php $user_manager->PrintErrors(); ?>
    <form method="post">
        <div>
            <label for="email">E-mail</label>
            <input type="email" name="email" id="email">
        </div>

        <div>
            <label for="password">Heslo</label>
            <input type="password" name="password" id="password">
        </div>

        <div>
            <input type="submit" value="Přihlásit" name="log_user">
        </div>
    </form>
</body>

</html>