<!DOCTYPE html>
<html lang="en">

<head>
    <?php require("./phtml/_defaultHeaderLinks.phtml"); ?>
</head>

<body class="account-page">
    <main>
        <div class="back-button" style="top: 20px"><a href="index.php"><i class="fa-solid fa-arrow-left"></i></a></div>
        <div class="form-wrapper">
            <div class="header">
                <h1>EVENTON</h1>
            </div>
            <form method="post" class="account-form">
                <h2>Přihlášení</h2>
                <div class="form-item">
                    <label for="email">E-MAIL</label>
                    <input type="email" name="email" id="email">
                </div>

                <div class="form-item">
                    <label for="password">HESLO</label>
                    <input type="password" name="password" id="password">
                </div>
                <?php if ($user_manager->GetErrorCount()) : ?>
                    <p class="error">
                        <i class="fa-solid fa-circle-exclamation"></i>
                        <?php $user_manager->PrintErrors(); ?>
                    </p>
                <?php endif ?>

                <div class="submit-container form-item">
                    <input type="submit" value="Přihlásit" name="log_user">
                </div>
                <div class="form-item links"><span>Nemáte účet?&nbsp;&nbsp;<a href="registration.php">Registrovat se</a></span></div>
            </form>
        </div>
    </main>
</body>

</html>