<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <script src="https://kit.fontawesome.com/4489d876da.js" crossorigin="anonymous"></script>
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.6.0/jquery.min.js"></script>
    <script src="./js/LoadMoreImages.js?v=<?= time(); ?>" type="text/javascript" defer></script>
    <script src="./js/PostScriptFunctions.js?v=<?= time(); ?>" type="text/javascript" defer></script>
    <script src="./js/NavigationMenu.js?v=<?=time(); ?>" type="text/javascript" defer></script>
    <link rel="stylesheet" href="css/style.css?v=<?= time(); ?>" type="text/css">
    <link rel="stylesheet" href="css/post-style.css?v=<?=time(); ?>" type="text/css">
    <title>Document</title>
</head>
<body>
    <?php require("./phtml/navigation.phtml"); ?>
    <div class="profile-data">
    </div>
</body>
</html>