<!DOCTYPE html>
<html lang="en">

<head>
    <?php require("./phtml/_defaultHeaderLinks.phtml"); ?>
    <script src="./js/min/ProfileImageLoad.min.js" type="text/javascript" defer></script>
    <script src="./js/min/PostScriptFunctions.min.js" type="text/javascript" defer></script>
    <script src="./js/min/NavigationMenu.min.js" type="text/javascript" defer></script>
</head>

<body>
    <main>
        <?php require("./phtml/navigation.phtml"); ?>
        <div class="profile-container">
            <div class="profile-info">
                <div class="user-info">
                    <img class="icon" src="<?= $_SESSION["user"]->GetUserIcon() ?>" alt="icon.jpg">
                    <div class="user-info-right">
                        <div class="username"><span class="text"></span><?= $_SESSION["user"]->GetUserName() ?></span><a href="settings.php" class="profile-edit-button">Upravit</a></div>
                        <div class="add-info">
                            <span class="info-item reg-date"><?= date("j.m.Y", strtotime($_SESSION["user"]->GetRegistrationDate())); ?></span>
                            <span class="info-item num-of-posts"><?= $_SESSION["user"]->GetNumberOfPosts() ?></span>
                            <span class="info-item num-of-likes"><?= $_SESSION["user"]->GetNumberOfTotalLikes() ?></span>
                        </div>
                    </div>
                </div>
            </div>
            <div class="profile-data-select">
                <div class="profile-data-select-item active" data-id="0"><i class="fa-solid fa-user-large"></i><span class="text">PŘÍSPĚVKY</span></div>
                <div class="profile-data-select-item" data-id="1"><i class="fa-solid fa-heart"></i><span class="text">OBLÍBENÉ</span></div>
            </div>
            <div id="posts-container">
            </div>
            <div id="loader-image" style="visibility:hidden;width:50px;margin:50px auto"><img src="images/LoadingGif.gif" style="width:50px;height:50px" alt="loader"></div>
        </div>
    </main>
</body>

</html>