<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <script src="https://kit.fontawesome.com/4489d876da.js" crossorigin="anonymous"></script>
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.6.0/jquery.min.js"></script>
    <script src="./js/LoadMoreImages.js?v=<?= time(); ?>" type="text/javascript" defer></script>
    <script src="./js/PostScriptFunctions.js?v=<?= time(); ?>" type="text/javascript" defer></script>
    <script src="./js/NavigationMenu.js?v=<?=time(); ?>" type="text/javascript" defer></script>
    <link rel="stylesheet" href="css/style.css?v=<?= time(); ?>" type="text/css">
    <link rel="stylesheet" href="css/post-style.css?v=<?=time(); ?>" type="text/css">
    <title>Document</title>
</head>
<body>
    <?php require("./phtml/navigation.phtml"); ?>
    <div class="profile-container">
        <div class="profile-data-select">
            <div class="profile-data-select-item active" data-id="0"><i class="fa-solid fa-user-large"></i></div>
            <div class="profile-data-select-item" data-id="1"><i class="fa-solid fa-heart"></i></div>
        </div>
        <div id="posts-container">
        </div>
        <div id="loader-image" style="visibility:hidden;width:50px;margin:50px auto"><img src="images/LoadingGif.gif" style="width:50px;height:50px"alt="loader"></div>
    </div>
</body>
</html>