<!DOCTYPE html>
<html lang="en">

<head>
    <?php require("./phtml/_defaultHeaderLinks.phtml"); ?>
</head>

<body class="account-page">
    <main>
        <div class="back-button" style="top: 20px"><a href="index.php"><i class="fa-solid fa-arrow-left"></i></a></div>
        <div class="form-wrapper">
            <div class="header">
                <h1>EVENTON</h1>
            </div>
            <form method="post" class="account-form">
                <h2>Registrace</h2>
                <div class="form-item">
                    <label for="username">UŽIVATELSKÉ JMÉNO</label>
                    <input type="text" name="username" id="username">
                </div>

                <div class="form-item">
                    <label for="email">E-MAIL</label>
                    <input type="email" name="email" id="email">
                </div>

                <div class="form-item">
                    <label for="password_1">HESLO</label>
                    <input type="password" name="password_1" id="password_1">
                </div>

                <div class="form-item">
                    <label for="password_2">OPAKOVAT HESLO</label>
                    <input type="password" name="password_2" id="password_2">
                </div>

                <?php if ($user_manager->GetErrorCount()) : ?>
                    <p class="error">
                        <i class="fa-solid fa-circle-exclamation"></i>
                        <?php $user_manager->PrintErrors(); ?>
                    </p>
                <?php endif ?>

                <div class="submit-container form-item">
                    <input type="submit" value="Registrovat" name="reg_user">
                </div>
                <div class="links form-item"><span>Už máte účet?&nbsp;&nbsp;<a href="login.php">Přihlásit se</a></span></div>
            </form>
        </div>
    </main>
</body>

</html>